#!/usr/bin/env bash
# Note: this script is intended to be executed inside a clean Alpine docker

source approvals.bash

# before all
git config --global user.email "approval@tester.com"
git config --global user.name "Approval Tester"

describe "usage"
  approve "rush" || return 0
  approve "rush --help"

describe "add"
  approve "rush add" || return 0
  approve "rush add -h"
  approve "rush add sample ~/rush-repos/sample-repo"
  approve "ls ~/rush-repos/sample-repo" "rush_add_ls"

describe "clone"
  rm -rf /root/rush-repos/dannyben
  approve "rush clone" || return 0
  approve "rush clone -h"
  
  approve "rush clone dannyben --shallow"
  count=$(cd /root/rush-repos/dannyben/rush-repo && git rev-list --count HEAD -n 10)
  [[ $count == 1 ]] || fail "Expected shallow clone, got $count commits"

  rush remove dannyben --purge >/dev/null
  approve "rush clone dannyben --shallow --name somename && rush config"

  rush remove somename --purge >/dev/null
  approve "rush clone dannyben --shallow --default && rush config"
  rush remove default --purge >/dev/null

  rush remove dannyben --purge >/dev/null
  approve "rush clone dannyben"
  count=$(cd /root/rush-repos/dannyben/rush-repo && git rev-list --count HEAD -n 10)
  [[ $count == 10 ]] || fail "Expected full clone, got $count commits"

  approve "rush clone dannyben" "rush_clone_dannyben_dir_exist" || return 0
  expect_exit_code 1

  approve "rush clone sample" || return 0
  expect_exit_code 1

  approve "rush clone sample --ignore"
  expect_exit_code 0

describe "config"
  approve "rush config"
  approve "rush config -h"

describe "default"
  approve "rush default" || return 0
  approve "rush default -h"
  approve "rush default sample"

describe "get"
  approve "rush add sample ~/rush-repos/sample-repo"
  approve "rush get" || return 0
  approve "rush get -h"
  approve "rush get hello"
  approve "rush get download"
  approve "rush get sample:hello"
  approve "rush hello"
  approve "rush get package-in-package/one"
  rush remove dannyben --purge > /dev/null
  approve "rush get dannyben:hello" || return 0
  approve "rush get dannyben:hello --clone"
  approve "rush get dannyben:hello" "rush_get_dannyben_hello_works"
  approve "rush hello --force"
  approve "rush hello --verbose"
  approve "rush get hello -fv"

describe "undo"
  approve "rush undo" || return 0
  approve "rush undo -h"
  approve "rush undo download"
  approve "rush undo sample:download"
  approve "rush undo sample:download --verbose"

describe "snatch"
  dir="/root/rush-repos/snatched"
  approve "rush snatch" || return 0
  approve "rush snatch -h"
  allow_diff "rush-snatch\.[0-9a-zA-Z]{6}"
  approve "rush snatch dannyben hello"
  allow_diff "rush-snatch\.[0-9a-zA-Z]{6}"
  approve "rush snatch dannyben hello --undo"
  allow_diff "rush-snatch\.[0-9a-zA-Z]{6}"
  approve "rush snatch dannyben hello --force --verbose"
  [[ -d $dir ]] && fail "Expected directory $dir to not exist"

describe "info"
  approve "rush info" || return 0
  approve "rush info -h"
  approve "rush info hello"
  approve "rush info sample:hello"

describe "pull"
  approve "rush pull" || return 0
  approve "rush pull -h"

describe "push"
  approve "rush push" || return 0
  approve "rush push dannyben --chmod" || return 0
  approve "rush push dannyben" || return 0
  approve "rush push --all" || return 0
  approve "rush push -h"

describe "remove"
  dir="/root/rush-repos/dannyben/rush-repo"
  approve "rush remove" || return 0
  approve "rush remove -h"
  approve "rush remove dannyben --purge"
  [[ -d $dir ]] && fail "Expected directory $dir to not exist"
  approve "rush remove dannyben"

describe "list"
  approve "rush list -h"
  approve "rush list"
  approve "rush list --simple"
  approve "rush list --all"
  approve "rush list --all --simple"
  approve "rush list hello"
  approve "rush list sample"
  approve "rush list nested"
  approve "rush list sample:nested"
  approve "rush list no-such-package"
  approve "COLUMNS=40 rush list"

describe "search"
  approve "rush search" || return 0
  approve "rush search -h"
  approve "rush search running"
  approve "rush search hello"
  apk del grep >/dev/null 2>&1
  approve "rush search busybox-error" || return 0

describe "edit"
  export EDITOR=cat
  approve "rush edit" || return 0
  approve "rush edit -h"
  approve "rush edit hello"
  approve "rush edit hello info"

describe "show"
  approve "rush show" || return 0
  approve "rush show -h"
  approve "rush show download"
  approve "rush show download main"
  approve "rush show nested"

describe "copy"
  mkdir ~/rush-repos/target
  rush add default ~/rush-repos/target > /dev/null
  approve "rush copy" || return 0
  approve "rush copy -h"
  approve "rush copy sample:hello"
  approve "ls ~/rush-repos/target/hello" "rush_copy_files_list"
  approve "rush copy sample:download download1"
  approve "rush copy sample:download default:download2" "rush_copy_sample_download_default_download2_1-of-2"
  approve "rush copy sample:download default:download2" "rush_copy_sample_download_default_download2_2-of-2" || return 0
  approve "rush copy sample:download default:download2 -f"
  approve "ls -R ~/rush-repos/target" "rush_copy_files_list2"

describe "completions"
  approve "rush completions"
  approve "rush completions -h"

