#!/usr/bin/env bash
set -e

check_file() {
  file="$1"
  if [[ ! -f "$file" ]]; then
    echo "ERROR: File not found $file"
    exit 1
  fi
}

get_comp_dir() {
  if [[ -d "/usr/share/bash-completion/completions" ]]; then
    echo "/usr/share/bash-completion/completions"
  elif [[ -d "/usr/local/etc/bash_completion.d" ]]; then
    echo "/usr/local/etc/bash_completion.d"
  else
    echo ''
  fi
}

# Check that 'rush' is in its place
check_file "/usr/local/bin/rush"

# Check that completions file is in place
compdir="$(get_comp_dir)"
if [[ -d "$compdir" ]]; then
  check_file "$compdir/rush"
else
  echo "ERROR: Cannot find compdir, completions not installed"
  exit 1
fi

# Check a couple of man pages
check_file "/usr/local/share/man/man1/rush.1"
check_file "/usr/local/share/man/man1/rush-get.1"

echo "Setup artifacts are OK"
