#!/usr/bin/env bash

print_in_color() {
  local color="$1"
  shift
  if [[ -z ${NO_COLOR+x} ]]; then
    printf "$color%b\e[0m\n" "$*"
  else
    printf "%b\n" "$*"
  fi
}

red() { print_in_color "\e[31m" "$*"; }
green() { print_in_color "\e[32m" "$*"; }
green_bold() { print_in_color "\e[1;32m" "$*"; }
blue() { print_in_color "\e[34m" "$*"; }

section() {
  printf "\n=== %s\n" "$(green_bold "$@")"
}

copy() {
  printf "%s => %s\n" "$(blue "$(printf '%-25s' "$1")")" "$2"
  cp "$origin/$1" "$2"
}

sudo_copy() {
  printf "%s => %s\n" "$(blue "$(printf '%-25s' "$1")")" "$2"
  $sudo cp "$origin/$1" "$2"
}

copy_executable() {
  sudo_copy "$1" "/usr/local/bin/"
  $sudo chmod a+x "/usr/local/bin/$1"
}

copy_man() {
  if [[ ! -d "/usr/local/share/man/man1/" ]]; then return; fi

  for file in "$1"/*.1; do
    sudo_copy "$file" "/usr/local/share/man/man1/"
  done

  if command_exist makewhatis; then
    $sudo makewhatis /usr/local/man
  fi
}

install_completions() {
  cmd="$1"
  dir="$2"

  if [[ -d "/usr/share/bash-completion/completions" ]]; then
    compdir="/usr/share/bash-completion/completions"
  elif [[ -d "/usr/local/etc/bash_completion.d" ]]; then
    compdir="/usr/local/etc/bash_completion.d"
  else
    compdir=''
  fi

  if [[ -n $compdir ]]; then
    printf "copying to %s\n" "$compdir"
    echo "eval \"\$($cmd)\"" | $sudo tee "${compdir}/${dir}" >/dev/null
  else
    printf "%s %s\n" "$(red WARN)" "skipping completions installation, compdir not found"
    echo "     install it manually by adding this to your startup script:"
    echo "     eval \"\$($cmd)\""
  fi
}

command_exist() {
  [[ -x "$(command -v "$1")" ]]
}

need() {
  command_exist "$1" || fail "Cannot run $1"
  printf "%s found\n" "$(blue "    $1")"
}

onerror() {
  local exit_status=$?
  printf "\n=== %s\n" "$(red "Aborted with exit status $exit_status")"
  exit $exit_status
}

fail() {
  printf "$(red 'ERR') %s\n" "$*"
  return 1
}

initialize() {
  set -e
  trap 'onerror' ERR

  # Figure out if we need sudo or not
  sudo=''
  if [[ $EUID -ne 0 ]]; then
    sudo='sudo'
  fi

  repo="$1"
  repo_url="https://github.com/${repo}.git"
  origin=$(mktemp -d)
}

section "Initializing"
initialize "DannyBen/rush-cli"

section "Checking for pre-requisites"
need git

section "Cloning $repo"
git clone --depth 1 "$repo_url" "$origin"

section "Copying files"
copy_executable 'rush'
copy_man 'doc'

section "Installing bash completions"
install_completions "rush_completions" "rush"

section "Done"
rush --version
